[search]
location = "Vancouver"
keywords = [
    "DevOps",
    "SRE",
    "Software Developer"
]
blacklisted_terms = [
    "Senior",
    "Lead",
]
blacklisted_companies = [
    "Google",
    "Meta"
]

[linkedin]
time_filter = 86400
distance = 0

[llm]
model = "gemma4"

[ranking]
minimum_score = 75

[resume]
text = "Paste text for the resume here"