[search]
location = "Vancouver"
keywords = [
    "DevOps",
    "SRE",
    "Software Developer"
]
companies_to_skip = [
    "Google",
    "Meta"
]

[linkedin]
time_filter = 86400
distance = 0

[llm]
provider = "ollama"
model = "gemma4"

[ranking]
minimum_score = 75

[resume]
text = "Paste text for the resume here"